name: Comment when opened

permissions:
  issues: write
  checks: read
  contents: read

on:
  issues:
    types:
      - opened
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue comment $ISSUE --body "Thank you for opening this issue, we'll review it ASAP."
        env:
          GITHUB_TOKEN: {% raw %}{{ secrets.GITHUB_TOKEN }}{% endraw %}
          ISSUE: {% raw %}{{ github.event.issue.html_url }}{% endraw %}
